### PR TITLE
DEPRECATED activity references killed from (almost) everywhere

### PR DESCRIPTION
**Pull request by balage1551**
It is done! :-)

Now only the built-in Jobs are refering to the old activities. 

In some cases, I used a temporal solution and still there is a dependency on Job type.
I made a temporal static function in AbstractActivityNEW:

    @Deprecated
    public static boolean isShipment(TourActivity activity) {
        return (activity instanceof JobActivity)
                        && (((JobActivity) activity).getJob() instanceof Shipment);
    }

This is called from any code I was not able to remove Job type dependency (mostly in tests and in the SolutionAnalyzer class). This makes it easier to handle them, because you can search where this function is called from.

### CODE REVIEW

**Comment by balage1551** [comment]
I introduced the 
## BIG RED BUTTON

If you push it (see `TheBigRedButton` class) the built-in jobs will generate new activities.

It allows us to switch on/off old and new style activity generation, so we can test.

(BTW, when I pushed the button, got 8 errors and 48 failures in tests. :-))

**Comment by balage1551** [comment]
I don't know what fails, on my computer all tests pass (with BRB not pressed).

**Comment by oblonski** [comment]
Thanks @balage1551 ... I am going to check which test fails and why

**Comment by balage1551** [comment]
> I don't know what fails, on my computer all tests pass (with BRB not pressed).

I'll check out as much as I can. (A size sign error I've already found.)
But don't worry, there will be plenty to fix for you. ;-)

**Comment by balage1551** [comment]
There is one more issue I would like to propose. It needs a moderately refactor, but it is illogical now.

The Service job is now the parent of the other three one (Break, Pickup and Delivery). Somehow I feel that it should be in level with them. Also, a suggestion from Joshua Bloch states that it is better to keep a common class abstract when it is not a functionality extention. 

What I suggest is to make Service abstract and rename it (my first idea to call it AbstractSingleActivityJob) and create a descedent called Service. The new abstract class could be a genric with the type of activity it creates and then the descedents could specify the Activity individually.

What do you think?

**Comment by oblonski** [comment]
Thanks for your suggestion. Sounds reasonable 👍.

**Comment by oblonski** [comment]
I d also like to refactor VehicleRoute. It basically manages a sequence of activities and the assigned vehicle. Currently, it depends very much on a list implementation thus one can retrieve activities at a position i in constant time. However, when it comes to inserting and removing activities, it is often much more favourable to use for example am adjaceny list. This is what I want to make configurable by abstracting TourActivities. I assume that if one has problems resulting in long route in terms of number of activities, it much better to switch to adjaceny list.

**Comment by oblonski** [comment]
Performance tests show that this list implementation of activities in vehicle route is currently no bottleneck. 2000k random .add and .remove operation on a route with 2000 acts takes less than 500ms (on my macbook). This is ridiculous comparing the size of the problem. Additionally, we usually have far less than 2000k .add and .remove operations (more 50k). Therefore, I think it is here not that important to switch to AdjancencyList.

**Pull request merged**
