### PR TITLE
Refactor AvgServiceAndShipmentDistance (remove Job intanceof dependency)

### PR DESCRIPTION
**Pull request by balage1551**
This is an example how to refactor code to remove some of the tight coupling of Job and the other part of the code. (Now it is almost overwhelming to introduce an new Job type, because of the wired-in in handling of the types.)

This solution makes the easiest approach: extending the Job interface. It is straightforward, but could break any possible out-of-framework implementation of Job, which doesn't inherite from AbstractJob. (However, I don't think it is possible to do any inheritence because of the tight coupling, so the risk is acceptable.)

@oblonski: Stefan, I wrote a more detailed email about the problem.

### CODE REVIEW

**Comment by karussell** [comment]
> @oblonski: Stefan, I wrote a more detailed email about the problem

Best would be to make this public (here or in the forum) to avoid that it gets lost or for others to read in the future

**Comment by oblonski** [comment]
@balage1551 can I post the problem you sent me per mail here?

**Comment by oblonski** [comment]
hi @balage1551, just to keep on changes, can we close this here and you make a new pull request with your cost refactoring? btw: just refactored the insertionIndex stuff: https://github.com/graphhopper/jsprit/commit/096b513aff4aae3fcdcfd49510eb18ce2f3e3e80 ... next I am going to look at how we can generalize insertion calculation. Best, Stefan

**Comment by balage1551** [comment]
>hi @balage1551, just to keep on changes, can we close this here and you make a new pull request with your cost refactoring? btw: just refactored the insertionIndex stuff: 096b513 ... next I am going to look at how we can generalize insertion calculation. Best, Stefan

Good work, Stefan! I saw you droped the Inserter at all. I'll have a look at the other stuffs if I have time on the weekend (or on Monday, latest). 

I'm not too practiced in pull requests and don't really know what do you wish from me? How can I revoke a pull request (the one about cost calculator)? Should I request a pull request on a different branch?

**Comment by oblonski** [comment]
this one tries to merge @balage1551 modifications into the master. I close this here. Would you mind to merge the latest job-activity-refactoring into your master and make a pull request again? Thanks a lot.

**Pull request closed without merging**
