### PR TITLE
Capacity is now Legacy :-)

### PR DESCRIPTION
**Pull request by balage1551**
I made Capacity class legacy and introduced SizeDimension, instead.

### CODE REVIEW

**Comment by oblonski** [comment]
Hooray 👍 Great! Thanks a lot.

**Comment by balage1551** [comment]
Now, I'll introduce the two field in Job Activity.

The unsigned one will be called `loadSize`, the signed one is `loadChange`. Is it ok? 

One question: what is the loadSize of an Exchange? The absolute value or the positive part of the loadChange?

**Comment by oblonski** [comment]
I am wondering whether we need `loadSize` in activities at all. Let us just start with `loadChange`. The current .getSize() are actually meant to be `.loadChange()`. Maybe we require smth like size in `AbstractJob` that gives us some more information about whether the job fits into the vehicle or not. For example, if the `max(sum(loadChange(act)) > vehicle.size`, it does not fit into the vehicle.

**Comment by balage1551** [comment]
> I am wondering whether we need loadSize in activities at all. Let us just start with loadChange. The current .getSize() is actually meant to be .loadChange(). Maybe we require smth like size in AbstractJob that gives us some more information about whether the job fits into the vehicle or not. For example, if the max(sum(loadChange(act)) > vehicle.size, it does not fit into the vehicle.

Some of the constraints are using this two: 

**PickupAndDeliverShipmentLoadActivityLevelConstraint:**

        if (newAct instanceof PickupActivityNEW) {
            SizeDimension newCapacity = loadAtPrevAct.add(newAct.getSize());
            if (!newCapacity.isLessOrEqual(vehicleCapacityDimensions)) {
                return ConstraintsStatus.NOT_FULFILLED;
            }
        }
        if (newAct instanceof DeliveryActivityNEW) {
            SizeDimension newCapacity = loadAtPrevAct.add(newAct.getSize().abs());
            if (!newCapacity.isLessOrEqual(vehicleCapacityDimensions)) {
                return ConstraintsStatus.NOT_FULFILLED_BREAK;
            }
        }

**ServiceLoadActivityLevelConstraint**

        if (newAct.getSize().sign() == SizeDimensionSign.POSITIVE) {
            if (!newAct.getSize().add(futureMaxLoad).isLessOrEqual(
                iFacts.getNewVehicle().getType().getCapacityDimensions())) {
                return ConstraintsStatus.NOT_FULFILLED;
            }
        }

        if (newAct.getSize().sign() != SizeDimensionSign.POSITIVE) {
            if (!newAct.getSize().abs().add(prevMaxLoad).isLessOrEqual(
                iFacts.getNewVehicle().getType().getCapacityDimensions())) {
                return ConstraintsStatus.NOT_FULFILLED_BREAK;
            }
        }

Ok. If we could live with these abs() calls, then it is really not necessary to use two.

**Comment by balage1551** [comment]
Or we could simply add the getLoadSize() function, but not the field, and the function could return the loadChange.abs() value for now. It would give us the chance to decide later and even change the implementation (cacheing the value into a field or calculate differently) later without breaking the code.

**Pull request merged**
