### PR TITLE
Refactored PickupServiceDEPRECATED at almost all its appearance.

### PR DESCRIPTION
**Pull request by balage1551**
There is one place where it is not simple to replace it:

`LoadAndActivityCounter` within `SolutionAnalyser`:

        @Override
        public void visit(TourActivity activity) {
            if (activity instanceof PickupActivityNEW) {
                pickupCounter++;
                pickedUp = pickedUp.add(((PickupActivityNEW) activity).getJob().getSize());
                if (activity instanceof PickupServiceDEPRECATED) {
                    deliverAtEndCounter++;
                }
            } else if (activity instanceof DeliveryActivityNEW) {
                deliveryCounter++;
                delivered = delivered.add(((DeliveryActivityNEW) activity).getJob().getSize());
                if (activity instanceof DeliverServiceDEPRECATED) {
                    pickupAtBeginningCounter++;
                }
            }
        }

Here we use it do decide whether it is a Shipment or a Service. 
I may be refactor it to `activity.getJob() instanceof`, but I feel this code should be overwritten entirely for generalization.
What do you see?

### CODE REVIEW

**Comment by oblonski** [comment]
I am going to refactor the SolutionAnalyzer. Thanks again.

**Comment by oblonski** [comment]
Thanks :)

**Comment by balage1551** [comment]
Almost finished to eliminate the old Activities.
When it is done, next we could switch the built-in Shipment and Service jobs to use the new ones...

... and that's when everything will go mayham!  

HAHAHAha....

**Comment by balage1551** [comment]
@oblonski : Are you currently work on SolutionAnalyzer? I would like to temporally rewrite it, if not.

**Pull request merged**
