### PR TITLE
orderNumber added

### PR DESCRIPTION
**Pull request by balage1551**
Somehow the pull request was not created a few hours ago.

### CODE REVIEW

**Comment by balage1551** [comment]
A minor, philosophical comment:

I feel awkward with the name Capacity since I first met it. 
Now I know why.

It is not a capacity. It is a type for Dimension or Size which is used in several places, for different purposes:

- In VehicleType, it is capacity
- On route (during optimalization) it is (current) load
- On activity, it is Size (unsigned) and loadChange (signed)

These anomaly is turned up as the code uses different name of the field in these classes (size in activity, capacity in vehicleType), and the need to use two methods in activities.

I would propose, that now, when the code falls through major refactor, it is the best time to make a consolidation. The only question, how exposed Capacity class is for third party codes? 
For jobs it is not a big issue, because usually the addSizeDimension (see, the function name is correct here ;-)) is used mostly and only the addAllDimension could be a problem. The constraints are different. I have not enough insight, whether capacity is reached frequently by third party constraints.

What do you think?

**Comment by oblonski** [comment]
When it comes to capacity, we need to think about alternatives anyway since currently capacity is ignored (see failing tests) since cap constraints do not know custom jobs. I like the idea of introducing unsigned and signed fields here. Then in all these constraints I only need to differentiate between capChange <0 and >=0 and I do not need to differentiate between job types anymore. 
To your observed anomalies, let us give it a more intuitive name (so I aggree with you). However, I d like to make sure that the old capacity name still works for a while. I do not have an overview about how often it is used in third party constraint. No idea. Probably SizeDimensions is a much better name than Capacity since items can have SizeDimensions, a vehicle type has SizeDimensions and the current load has SizeDimensions as well?

**Comment by balage1551** [comment]
> When it comes to capacity, we need to think about alternatives anyway since currently capacity is ignored (see failing tests) since cap constraints do not know custom jobs. I like the idea of introducing unsigned and signed fields here. 

Your algorithm code never has to know anything about Job types (because there could be any new job type). It only has to operate by activities and their job could be used as long as it is handled as AbstractJob. (No use of instanceof, but it can use any of the methods offered by AbstractJob, such as accessing the JobActivityList to get all the activities of the Job.)

On activities, I'll introduce the two fields (signed and unsigned).

> Then in all these constraints I only need to differentiate between capChange <0 and >=0 and I do not need to differentiate between job types anymore.

I've already given a new method to Capacity: `isPositive()`. If you need >=0, then it could be altered to `isNegative()`, although. Also, because the set of Activities are fixed and all job activities are derived from the four base one: service (change == 0); pickup (change > 0); delivery (change < 0); exchange (change +/-/0), if you can't avoid, you can use the instanceof on these base types. Or, if you would like to avoid instanceof, we could introduce a ActivityKind enum and give it to all Activity types and use it. The difference is that you can give these enums special behavoiur according the type. 

However, it brought up a problem I haven't thought before. I introduced the ExchangeActivity, but it would raise a problem. It was meant to represent cargo swap: you unload something and load something else at the same time. Therefore, it could represent a zero, a negative or a positive cargo change. It has no problem, but it also can represent a mixed one: some of the dimensions are negative, some of the dimensions are positive. And this could lead to problems as far as I see. If you can't easily handle this now, we could simplify the problem by stating either that all dimensions should have the same sign or declare that exchange has the size impact of 0 (meaning it always picks the same sized cargo as it delivers). (This anomaly only stands if you need to check positive/negative cargo change size anywhere in the code.)

> To your observed anomalies, let us give it a more intuitive name (so I aggree with you). However, I d like to make sure that the old capacity name still works for a while. I do not have an overview about how often it is used in third party constraint. No idea. Probably SizeDimensions is a much better name than Capacity since items can have SizeDimensions, a vehicle type has SizeDimensions and the current load has SizeDimensions as well?

My suggestion to be backward compatible: 

- Create the new class `SizeDimensions` (I like the name, but do we need plural? As name convention, plural forms usually represents static utility classes, such as Arrays, Collections.)
- Let the old `Capacity` class be a non-code extention of the `SizeDimensions` class and be deprecated.
- Keep the `Capacity.Builder`, but as a deprecated, non-code extension of SizeDimensions.Builder.

**Comment by oblonski** [comment]
> On activities, I'll introduce the two fields (signed and unsigned).

Perfect, @balage1551. Thanks a lot.

> My suggestion to be backward compatible:
> 
>     Create the new class SizeDimensions (I like the name, but do we need plural? As name convention, plural forms usually represents static utility classes, such as Arrays, Collections.)
>     Let the old Capacity class be a non-code extention of the SizeDimensions class and be deprecated.
>     Keep the Capacity.Builder, but as a deprecated, non-code extension of SizeDimensions.Builder.
> 

Good idea. We can name it **SizeDimension**.

To Exchange Act: My opinion here is that if we are too strict, we do not need Exchange act at all since it can then be replaced either by pickup, delivery or service. I think that Exchange might make sense if we allow negative and positive values at the same time. It might be negative (delivery) in one dimension and positive (pickup) in another?

**Comment by balage1551** [comment]
> For example, Exchange makes sense if you bring Apples and get Bananas in return. It does not have much value if you bring Apples and in return you get more Apples since this can be modelled by Pickup (Apples`-Apples).

I totally agree with you. I've only feared that this could cause some problem in your code. For example, the `isPositive()` and/or `isNegative()` function should be replaced by a `sign()` function with four possible result: POSITIVE, ZERO, NEGATIVE or MIXED.
But I have a better idea: what about, if the Exchange would contain two SizeDimension fields: one for unload, one for the new load? The these two could be kept with definite sign. (Naturally they could be the same with different sign.)

**Comment by oblonski** [comment]
Hmm. I fear that if we introduced this, actually using this might imply that I always need to check whether there are two dim fields or not. Difficult. Let me first remove all job type dependencies from the contraints ...

**Comment by balage1551** [comment]
>Hmm. I fear that if we introduced this, actually using this might imply that I always need to check whether there are two dim fields or not. Difficult. Let me first remove all job type dependencies from the contraints ...

You know your code better. Choose which is less problematic: having sizeDimension with mixed sign or having two sizes.

**Comment by oblonski** [comment]
Lets start with mixed sign

**Comment by balage1551** [comment]
> Lets start with mixed sign.

Ok. I'll do them.

**Comment by oblonski** [comment]
@balage1551: What do you think of introducing two new methods to AbstractJob: getPickupAtStart() and getDeliveryAtEnd(). We should easily calculate them when caching locations/timeWindows from activities by summing up each activities` capacity. If a dimension is < 0 it needs to be picked up at start of vehicle, if it is > 0 it will be delivered to end of vehicle. For ordinary shipments, getPickupAtStart() and getDeliveryAtEnd() amount to [0,0,...]. For a single Delivery activity, getPickupAtStart()=sizeOf(Delivery) etc. What do you think?

**Comment by oblonski** [comment]
Or we name it getSizeAtStart() and getSizeAtEnd()?

**Comment by oblonski** [comment]
here is an example: https://github.com/graphhopper/jsprit/commit/1844f2de40298475f1b7c6e407ef5e09d8ddd9ef?diff=split

**Comment by balage1551** [comment]
>What do you think of introducing two new methods to AbstractJob: getPickupAtStart() and getDeliveryAtEnd(). We should easily calculate them when caching locations/timeWindows from activities by summing up each activities` capacity. If a dimension is < 0 it needs to be picked up at start of vehicle, if it is > 0 it will be delivered to end of vehicle. For ordinary shipments, getPickupAtStart() and getDeliveryAtEnd() amount to [0,0,...]. For a single Delivery activity, getPickupAtStart()=sizeOf(Delivery) etc. What do you think?

Am I right, that the difference between a single Delivery job and a Shipment that it pick up its cargo at the depo instead of from a specified location? If so, I agree your idea. I like the getSizeAtStart() and getSizeAtEnd() better as names.

**Comment by oblonski** [comment]
> Am I right, that the difference between a single Delivery job and a Shipment that it pick up its cargo at the depo instead of from a specified location?

Exactly. At some location the items to be delivered need to be picked up. If there is no specific pickup location (as when having a Shipment), it is assumed to be picked up at the start location/depot of the vehicle.

**Comment by oblonski** [comment]
fyi. this is new functionality: https://github.com/graphhopper/jsprit/commit/90ad13a33dbccc4e07f1fb95e3fb370b9addd8d4
here are the acc commits: https://github.com/graphhopper/jsprit/commit/6c599afa8122bec179c0495a9eec5b4c491b2b26

**Comment by balage1551** [comment]
>fyi. this is new functionality: 90ad13a
here are the acc commits: 6c599af

Good stuff. (I'll have some conflicts on Capacity. ;-) )

**Comment by oblonski** [comment]
I can resolve this if you want :)

**Comment by balage1551** [comment]
No problem, I can do it.

**Comment by balage1551** [comment]
The merge was harder than I thought, because I renamed Capacity and replaces all the occurencies  of Capacity to SizeDimension. 43 conflicts. (Finally I did the easy way: stashed my Capacity and SizeDimension classes, accepted all your changes, applied stash and replaced Capacity again.

I was able to do the class name switch transparent, backward compatible and still keeping Capacity lightweigth thanks for the Builder pattern.

**Pull request merged**
