### PR TITLE
All tests pass with the Big Red Button pressed (with new Activities)

### PR DESCRIPTION
**Pull request by balage1551**
This is a milestone: all tests completed successfully with the jobs creating the new type of activities.

Now it's time to remove the last references to the old ones.

### CODE REVIEW

**Comment by balage1551** [comment]
Almost cleared all deprecated methods from Jobs.
One question has risen: there is a family of methods in VehicleRoute called addXXX().
It has a two parameter version with timeWindow. With the other one, the one without timeWindow parameter, has some problem: what is really the intention of this method? Which time window has to be used? Or is it a backward compatible solution from the time when only one time window was allowed? 

Is it ok, to check the number of time windows and throw exception when there is more than one? Also, may I mark this functions as obsolete?

**Comment by balage1551** [comment]
Another question: ˛`getSize()`
It is declared on `Job` interface and intensively used in several palces from Cost canculators, till readers and analyser.
For `AbstractSingleActivityJobs` and `Shipments` it has meaning (also for internal Jobs like break and Start/End it could be interpreted as EMPTY), but for a general Job such as ReturnedShipment, it hasn't any well defined meaning. It means that it is not safe anymore to base any logic on this fuction and should be eliminated.
However, while all the other deprecated functions could have been replaced by delegating to the correspondant activities, this can't be refactored so easily.

What is your opinion?

**Comment by oblonski** [comment]
Hi @balage1551,
To your first question: The method without dates from version without multiple time windows. You can deprecate it.
To your second question: I d suggest to deprecate it and we will see how we can reasonably replace it. As I mentioned somewhere, it might make sense to give some general information about size on job level. Maybe we can also remove it entirely. I need to analyse the impacts of deprecating first. Thanks againg.

**Comment by balage1551** [comment]
> I d suggest to deprecate it and we will see how we can reasonably replace it. As I mentioned somewhere, it might make sense to give some general information about size on job level. Maybe we can also remove it entirely. I need to analyse the impacts of deprecating first. Thanks again.

I'll keep it, but each job has to implement its own "meaning of job size". Or if you can think of some general definition (like the maximum (or the maximum of the absolute value) of all sizes of each activities, then we could give a default implementation. But to validate any definition, you need check how it is used.

**Comment by oblonski** [comment]
Thanks @balage1551

**Pull request merged**
