### PR TITLE
ActivityContext without insertion index for shipment delivery activities

### PR DESCRIPTION
**Pull request by Jullil**

### CODE REVIEW

**Comment by oblonski** [comment]
Great! Thanks a lot. We are going to switch from LGPL to the much more commercial friendly Apache license. In the course of this, you need to sign a contributor license agreement. I will sent this tomorrow. Thanks again!

**Comment by oblonski** [comment]
@Jullil Would you mind to send an email to info@graphhopper.com so that I have your email to send you the license agreement? Thanks.

**Comment by Jullil** [comment]
Sure. I've sent an email to this address.

**Comment by oblonski** [comment]
Perfect! Thanks a lot!

**Pull request merged**
