### PR TITLE
Service relocated

### PR DESCRIPTION
**Pull request by balage1551**
This refactor had a rather wide impact on files. 
All tests are passed, but had to change the activity type of Service from Pickup to Service, so the Big Red Button has no effect on this job type.

### CODE REVIEW

**Comment by balage1551** [comment]
A question about tests:
Is BelhaizaReader.testAlgo() test important?
It takes about 60% of the time of all tests. Testing would be much faster if we ignore this single test case.

**Comment by balage1551** [comment]
A big, philosophical question:
The constructor og the DeliveryActivityNEW should get 

1. an already negated size
2. a positive size and it negates
3. any size and if it calls abs().invert() on it (== accept both, but stores always negative)

**Comment by oblonski** [comment]
When it comes to Delivery it is more intuitive to let the user construct it with positive size value in the sense of "deliver 5 tonnes fish" and not "deliver -5 tonnes fish". Therefore, I negated the value within constructor. Here, however, we get in conflict with Exchange since it assumes to pickup and deliver items. If we do it with a single size dimension, users should specify deliveries as negative values, otherwise we should differentiate between a pickup and delivery part.

**Comment by oblonski** [comment]
However, since building a job can be decoupled from activities and activities are lower level, we can also specify it such that there is no need to change signs, i.e. construct Deliveries with negative values.

**Comment by balage1551** [comment]
> When it comes to Delivery it is more intuitive to let the user construct it with positive size value in the sense of "deliver 5 tonnes fish" and not "deliver -5 tonnes fish". Therefore, I negated the value within 
constructor. 

Ok, I agree. I'll fix the code to accept positive size and then negate the values inside.

> Here, however, we get in conflict with Exchange since it assumes to pickup and deliver items. If we do it with a single size dimension, users should specify deliveries as negative values, otherwise we should differentiate between a pickup and delivery part.

This is not a big issue, because the user will only create activities in his code when he creates a new Job type.

In the ReturnedShipment built-in Job, there is separated size for delivery and backhaul and the createActivities calculates the difference between the two. 

To help the developers using the Exchange activity in their own Job types, I will make a new, convenient constructor with two size paraneters. (And for the same safety, I would prefere the (3) option and check the sign of the size parameter and negate if it is needed.)

**Pull request merged**
