### PR TITLE
Capacity refactor

### PR DESCRIPTION
**Pull request by balage1551**

### CODE REVIEW

**Comment by oblonski** [comment]
Wow. You are lightning-fast ;). Great. Thanks a lot.

**Comment by balage1551** [comment]
I'll soon need the new features, so I try to help as much as I could. (And I don't know how much longer I get the permission to work on this free project on official time. ;-)) 
Do you have any guess, how much work to make the generic job feature to run? (I don't need production ready state, I only need the results calculated, not the lib itself.)

**Comment by oblonski** [comment]
ok. I pushed the version of the GeneralJobInsertionCalc: https://github.com/graphhopper/jsprit/commit/db808c4802c981e62e88a712bdb546c676be1b4b
It comes with significant obj/list creation overhead. I will be streamlining it. However, [my first custom job](https://github.com/graphhopper/jsprit/blob/job-activity-refactoring/jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/FirstCustomJobExample.java) example runs fine :). Additionally, the code of the insertion calc is much nicer now. However, it might take some time to understand the recursive approach. 
Next I will check what happens with the core constraints, when working with custom jobs.

**Comment by oblonski** [comment]
> (I don't need production ready state, I only need the results calculated, not the lib itself.)

Have you already started to solve your original problems?

**Comment by balage1551** [comment]
> Have you already started to solve your original problems?

Thanks for asking. I'm still doing synthetic tests but they goes well.

Yesterday, I was on holiday, but today I'm creating a generic job based on your CustomJob and not only for testing. That is a great idea for creating new Job types when you don't need any additional functionality, only more activities in them. I make it to support all the activity features, such as time windows, operation time, custom name. 

One question I would gladly hear your opinion:
Because there are too many optional values for activities (operationTime, tw, size, name, etc.) it creates an overload-boom if we would like to support it by addXXX() functions. Therefore, it is better to parameterize as a builder, too. But it is a builder-in-builder and if you would like to keep the fluent api of a builder, you have to make some tricks. 
There are two options:

First is to have a termination function of the inner builder (Don't see the name of the class, it will be CustomJob after I replaced your old one.):

    GenericCustomJob.Builder.newInstance("job")
                        .addPickup(Location.newInstance(10, 0)).withSize(SizeDimension.of(1)).withTimeWindow(TimeWindow.newInstance(0, 30))**.finish()**
                        .addExchange(Location.newInstance(5, 30))**.finish()**
                        .addDelivery(Location.newInstance(10, 0)).withSize(SizeDimension.of(1))**.finish()**
                        .build());

What here really happens is that addXXX() returns a reference of the inner builder, so you can call its adders, but to return to the outer (job) builder, I need a finish() function:

    class BuilderActivityInfo {
       [...]
             public BuilderBase<T, B> finish() {
                 return BuilderBase.this;
             }
    }

The other option is to tear off the inner builder. Then the above call would look like:

    GenericCustomJob.Builder.newInstance("job")
                        .addActivity(new BuilderActivityInfo(ActivityType.PICKUP, Location.newInstance(10, 0))
                                        .withSize(SizeDimension.of(1))
                                        .withTimeWindow(TimeWindow.newInstance(0, 30)))
                        .addActivity(new BuilderActivityInfo(ActivityType.EXCHANGE, Location.newInstance(5, 30)))
                        .addActivity(new BuilderActivityInfo(ActivityType.DELIVERY, Location.newInstance(10, 0))
                                        .withSize(SizeDimension.of(1)))
                                        .build())

Which way do you prefer?

**Comment by balage1551** [comment]
I made the decision: a little of this, a little of that. :-)

I use the second option, but created some (not all variation) of typed constructors:

        public GenericCustomJob.BuilderBase<T, B> addPickup(Location location) {
            add(ActivityType.PICKUP, location, 0d, null, null, null);
            return this;
        }

        public GenericCustomJob.BuilderBase<T, B> addPickup(Location location, SizeDimension size) {
            add(ActivityType.PICKUP, location, 0d, size, null, null);
            return this;
        }

        public GenericCustomJob.BuilderBase<T, B> addPickup(Location location, SizeDimension size, double operationTime) {
            add(ActivityType.PICKUP, location, operationTime, size, null, null);
            return this;
        }

        public GenericCustomJob.BuilderBase<T, B> addPickup(Location location, SizeDimension size, double operationTime,
                        TimeWindow tw) {
            add(ActivityType.PICKUP, location, operationTime, size, null, Collections.singleton(tw));
            return this;
        }

This allows to use the general addActivity() if you need special parameterizing, but could use the shorthand forms most of the time. There is a "order" among the parameters (according my guess of how often they are used): location (required) -> size -> operationTime -> a single time window. If you need one of them, all preceeding ones should be supplied as well. Is the order correct? In real life, doesn't time window is more often used, than operation time?

**Pull request merged**
