### PR TITLE
#347 - Custom properties

### PR DESCRIPTION
**Pull request by balage1541**
I've implemented the request in Vehicle, VehicleType, Location and in the Job classes.
Added some unit tests as well.

_I've tried hard to keep formatting, but in some cases it was impossible, so there is some unchanged lines marked as changed._

Still need to migrate this feature to the new branch.

### CODE REVIEW

**Comment by oblonski** [comment]
Great! Thanks.

**Comment by carhartl** [comment]
Would it make sense to add the `setUserData()` and `getUserData()` methods to the job interface? This would allow me to do the following:

```java
Job job = (Job) ((TourActivity.JobActivity) tourActivity).getJob();
job.getUserData(); // I may not care about the type of job (service, shipment, ...)
```

Right now I have to do this:
```java
Job job = (Job) ((TourActivity.JobActivity) tourActivity).getJob();
if (job instanceof Service) {
    ((Service) job).getUserData();
} else if (job instanceof Shipment) {
    ((Shipment) job).getUserData();
}
```
(There could be a nicer way to do this anyway...)

Alternatively, casting to an abstract (more of internal?) class kind of felt dirty:

```java
AbstractJob job = (AbstractJob) ((TourActivity.JobActivity) tourActivity).getJob();
job.getUserData();
```

**Comment by balage1551** [comment]
Thanks, your suggestion makes sense. However, this version of Jsprit is Java7 complient, which means, adding a new method to an interface may break any implementation based on it. (All user defined Job types.)

Jsprit 2 will be built on Java 8, so there we could extend an interface by adding default implementation. Surely we will do it.

As for the current version, you have to take some unconfortable casting for the sake of backward compatibility. By the way, the AbstractJob is not private api, but a minimal base for all job implementation, so don't feel guilty to cast on it!

**Comment by carhartl** [comment]
Makes sense 👍

**Comment by carhartl** [comment]
Btw, do you consider semantic versioning in this project?

**Pull request merged**
