### PR TITLE
Xml : Distance available

### PR DESCRIPTION
**Pull request by braktar**
It make distance available at the top level in order to have a quick view on the solution quality instead of only cost or time.

cumulated time and distance are now available at the same level as the cost in the xml

### CODE REVIEW

**Comment by oblonski** [comment]
Wow. You are super active 👍 . Thanks a lot @braktar. I will have a look at your pr the next days. Actually, that distance is not part of activities etc. is by purpose ;). But let us discuss whether it is more convenient and necessary to have this extension.

**Comment by braktar** [comment]
This is convenient to return the total distance, we have all the informations available in Jsprit otherwise we have to recompute the route which could imply to request the data again.
But currently it enforce to maintain the correctness of it during the solve. It could be interesting to only calculate it once we ask the solution.

**Comment by oblonski** [comment]
Hi @braktar, why do you want to extend activities and solution obj with distance? Do you have a specific reason? You can always add a new distance state and get the distance with the stateManager. I understand that you want to have it in your xml result file, but here you can calculate distance just before writing the xml file ...
The reason I ask is that I do not want to add a new core state and new fields in activities just because it is more convenient. Since it also more convenient to have load information in each activities etc.. However, what is convenient or not is - as I think - very much dependent on the use case. Therefore, the idea is to keep activities as lean as possible, but add a way to associate activities with states as you can do with the StateManager. But as I wrote I understand that you want to have distance in your xml file or result statistic. Here, you can easily use the SolutionAnalyser and write distance also. 
What do you think?

**Comment by braktar** [comment]
Hi,

I had in mind to have some constraints based on the total distance of a route.
For the actual case of use, a simple calculation into the SolutionAnalyzer seems more convenient. ;)

**Comment by oblonski** [comment]
BTW: If you want to extend the XmlWriter with the "most important" additional indicators like distance I do not mind to merge this into the master. Just calculate e.g. distance just before writing the xml file.

**Pull request closed without merging**
