### PR TITLE
Modular objective function (SolutionCostCalculator)

### PR DESCRIPTION
**Pull request by balage1551**
Here is the basic implementation of the modularization of the cost function.
What have changed:

(1) A new class hierarchy introduced based on the root class `SolutionCostComponent`. All implementations are responsible to calculate an aspect of the objective function. The base implementation does it by the abstract 

    public abstract ComponentValue calculateCost(VehicleRoutingProblem problem,
                          VehicleRoutingProblemSolution solution);

function. There is a subclass of this called `RouteLevelSolutionCostComponent` which calculates and keeps track of the costs per route level. (Here the above function is implemented and the new, abstract 

    protected abstract double calculateRouteLevelCost(VehicleRoutingProblem problem, 
                           VehicleRoute route);

function should be implemented.

(2) To cover the current cost components, there are five component implementations: 

- FixCostPerVehicle (non route level)
- MissedBreak (route level)
- TransportCost (route level)
- ActivityCost (route level)
- UnassignedJobs (non route level)

As for the current commit, none of the above has any parameter, but some of them could be extended to support customization (such as the cost impact per priority level for unassigned jobs).

I could think of some other useful implementations:

- VehicleUtilization: a route level cost, which penaltize when the vehicle utilization (active time) is diverge from a given value. For example, we would like the vehicles are utilized for 80 % of their time. If this value is lower (more idle time), it is not cost effective, if it is higher, they may be overloaded and the optimalization is fragile for uncalculated problems.
- Overload penalty: add cost when the load level of the vehicle is exceeding a value. For example, the vehicle could carry 10 units, but over 8 units it is unefficient.

And surely there are others, I didn't think about.

(3) A new class **`ModularSolutionCostCalculator`** (implements SolutionCostCalculator) is created. 
It has the following features:
- The user could add any component to it.
- Each component could have a weight value.
- It completely backward compatible with the old `SolutionCostCalculator` (`getCosts()` aggregates the component cost values), but stores the per component information as well.
- Supports `beforeRun()` and `beforeSolution()` for global and perSolution initialization. (still needs to be wired in)

(4) Modified the Jsprit wrapper to used the new cost calculator:

    private SolutionCostCalculator getObjectiveFunction(final VehicleRoutingProblem vrp, final double maxCosts) {
        if (objectiveFunction != null) {
            return objectiveFunction;
        }

        ModularSolutionCostCalculator modCalc = new ModularSolutionCostCalculator(vrp, maxCosts);
        modCalc.addComponent(new FixCostPerVehicle())
        .addComponent(new MissedBreak())
        .addComponent(new TransportCost())
        .addComponent(new ActivityCost())
        .addComponent(new UnassignedJobs());

        // TODO: temporal, not to do here!
        modCalc.beforeRun();
        modCalc.beforeSolution();

        return modCalc;
    }

(5) Extended the `VehicleRoutingProblemSolution` class to hold the detailed data if available (backward compatible).

(5) Added a new block to the SolutionPrinter: 

    public static void printCostDetails(PrintWriter out, VehicleRoutingProblem problem, 
                   VehicleRoutingProblemSolution solution);

This prints detailed cost info when the information is available on the solution:

	+--------------------------+
	| Solution                 |
	+----------------+---------+
	| indicator      | value   |
	+----------------+---------+
	| costs          | 9893,78 |
	| noVehicles     | 2       |
	| unassignedJobs | 1       |
	+----------------+---------+

	+--------------------------------------------------+
	| Cost components                                  |
	+--------------+---------+--------+----------------+
	| component id | value   | weight | weighted value |
	+--------------+---------+--------+----------------+
	| VehicleFix   |    0,00 |   1,00 |           0,00 |
	| MissedBreak  |    0,00 |   1,00 |           0,00 |
	| Transport    | 4412,00 |   2,00 |        8824,00 |
	| Activity     |    0,00 |   1,00 |           0,00 |
	| Unassigned   | 2139,56 |   0,50 |        1069,78 |
	+--------------+---------+--------+----------------+

	+-------------------------------------------------------------------+
	| Route level costs (weighted)                                      |
	+-------+------------+-------------+-----------+----------+---------+
	| Route | VehicleFix | MissedBreak | Transport | Activity | Total   |
	+-------+------------+-------------+-----------+----------+---------+
	| 1     |       0,00 |        0,00 |   4876,00 |     0,00 | 4876,00 |
	| 2     |       0,00 |        0,00 |   3948,00 |     0,00 | 3948,00 |
	+-------+------------+-------------+-----------+----------+---------+
	| Total |       0,00 |        0,00 |   8824,00 |     0,00 | 8824,00 |
	+-------+------------+-------------+-----------+----------+---------+

Also I gave the route a fixed number when it is added to a solution. This route number is now used in several places (printer, detailed costs), so it is better to keep it centralized.

Hope you will like to these new features. (I'll make some additional features now, but the core is ready.)

### CODE REVIEW

**Comment by balage1551** [comment]
I've added the missing pieces:

(1) Put the `beforeSolution()` and `beforeRun()` function to their right places.
(2) Added a static function to get a copy of the default function: 

    ModularSolutionCostCalculator modCalc = Jsprit.createDefaultSolutionCostCalculator();

(3) Added functions to manage calculator: `addComponent` (adds a component), `findComponent` (finds a component), `containsComponent` (checks if the component is in), `changeComponentWeight` (modifies the weight of a component) and `removeComponent` (removes a component). Now the user could build up a cost function like this:

        ModularSolutionCostCalculator modCalc = Jsprit.createDefaultSolutionCostCalculator();
        modCalc.removeComponent(MissedBreak.COMPONENT_ID);
        modCalc.changeComponentWeight(TransportCost.COMPONENT_ID, 2d);

        vrAlgorithm = Jsprit.Builder.newInstance(vrProblem).setObjectiveFunction(modCalc).buildAlgorithm();


(4) Only `beforeRun()` initializes the problem specific part of the calculator, so user can build up a function before anything else. 

Now it is completely functional.

Note: for backward compatibility, I used the following idioms where I operate with the CostCalculator:

        if (objectiveFunction instanceof ModularSolutionCostCalculator) {
            ((ModularSolutionCostCalculator) objectiveFunction).beforeRun(vrp, maxCosts);
        }

If we decide to drop old style `SolutionCostCalculator` these code snippets could be removed, but one more thing the user have to migrate when switching to the new version. Other option is to add the new functions `beforeRun`, `beforeSolution`, etc to the `SolutionCostCalculator` interface with a dummy, empty, default implementation. (Java8 feature)

**Comment by oblonski** [comment]
Hi @balage1551, Thanks a lot. I am going to review this tomorrow. Best, Stefan

**Comment by oblonski** [comment]
Very nice :). Thanks @balage1551. I understand .beforeRun(), but what is your intention of .beforeSolution()? Best, Stefan

**Comment by balage1551** [comment]
`beforeSolution()` is for any stateful components. (As for now, there is none.)
For example, you would like to calculate some kind of average or percentile, but per route level. Now you can calculate the sum of the solution once in beforeSolution() store it in a field and use it in the `calculateRouteLevelCost()` function.

**Comment by oblonski** [comment]
Just a side note that might be important here: the objective function influences the final solution significantly, thus if you have like 100 solutions, solution i that min/max the objective function is likely to be selected. However, to create these solutions, the local search procedure (ruin and recreate/insertions) is applied that guides the algorithm to promising solutions in the search space. Therefore, "good" results are only achieved if search procedure and objective function work together, i.e. aiming similar directions. For example, if the objective aims at the deployment of blue vehicles and the local search produced does not consider this and solely aims at inserting service where costs are low, the overall results might not be what you expected.

**Comment by oblonski** [comment]
BTW: I am sure that there is a way to account for this more efficiently by coupling objective function and search procedure. I just do not know exactly how ;).

**Comment by balage1551** [comment]
Yes, that is something I suspected and wanted to ask. :-)
I was just wanted to ask whether we could unify them in some way, but I see it is not that straightforward.
After two months in the code, I'm still a beginner in the core algorithm code, so I can't help here, only by giving some wild guesses and letting you to decline it or not.

As a first step, without the wish to make it in one step, can the search function be modulized is some way?

**Comment by oblonski** [comment]
I am sure that this is possible. I d suggest to release this first at the beginning of next year and then analyse where we could impove/simplify next. Search process, constraints and StateManager is definitely where I see some potentials to improve ;), but lets do it step by step.

**Pull request merged**
