### PR TITLE
Setup time

### PR DESCRIPTION
**Pull request by braktar**
Setup time once a location is reach for the first time in a direct sequence.

Typically Unloading/Reloading at a same place but only have to setup the truck at arrival.

### CODE REVIEW

**Comment by oblonski** [comment]
Thanks a lot. What is the reasoning behind this? Would you mind to explain it?

**Comment by PGWelch** [comment]
If I'm understanding this correctly, it would correspond to "parking the car" time or "knocking on the door" time when you have multiple stops at the same location - which can happen (probably more common with pickup-delivery problems). It definitely makes sense to implement this kind of functionality - although presumably it could be done by client code so its debatable whether it should be in core jsprit or not.

**Comment by oblonski** [comment]
Ok. Understood. However, location is comparably low level. I think that setup time is not only dependent on location but also on vehicle, day time correlating to available parking space etc.. As I understand this correctly, it is implemented so that it is just a markup to transport time. Wouldnt it make more sense to implement this directly in VehicleRoutingTransportCosts/ActivityCosts? And if it is related to the actual job, then it should be considered in the activity duration of the job? What do you think?

**Comment by oblonski** [comment]
For example, one way to achieve this is by defining an array memorizing setup time markups according to location indeces. This array can then directly put in your custom VehicleRoutingTransportCost implementation.

**Comment by braktar** [comment]
You get it, the setup time is the time the vehicle need to prepare himself from the incoming sequence of load/unload. In my case it the time to load every pickup to deliver in the route.

My though was that this setup time is directly linked to the location and independent from the activity performed. But now you told we can imagine a case were this setup time could be dependent from the order of loading/unloading. This make it a bit more high level. But does it make sense to assign it at the job level ?

**Comment by oblonski** [comment]
I think that setup time/time to load/unload/time to park or whatever is never solely dependent on the location. The location is just a geo reference. How long it takes there to conduct an activity is - in my view - always dependent on the environment, i.e. type of activity, number of freight units to load, vehicle, driver knowledge, parking space, day time etc.. Therefore, I would avoid to put it directly into a location and thus bind it to a certain geo code. What if you had two activities at the same location with different setup times? If you really want to make this location dependent, you can do so with a simple location --> time-markup mapping (use array) in your transport time definition where you can even make it dependent on vehicle, arrival and departure time.

**Comment by oblonski** [comment]
@braktar Just give a more detailed explanation of your concrete use case so that we can discuss alternative approaches or if it appears that there is no alternative to just implement it - as you suggested - in location.

**Comment by braktar** [comment]
Yep, that's what your comments enlight to me. I totally agree, the Location level is not the good way to do it.

I'm looking to implement it, at first, in the Shipment definition, because it's mainly in this situation it could happen. And call it in the transport time definition.

**Comment by braktar** [comment]
Hmpf...

I've edited all the class calling getTransportTime or getBackwardTransportTime but it still doesn't give correct results.

Is there another mechanism to update it through the resolution ?

**Pull request closed without merging**
